"""Render the authoritative Python corpus for Dart; never invent expectations."""

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def build_vectors():
    manifest_bytes = (ROOT / "corpus-manifest.json").read_bytes()
    pin = json.loads((ROOT / "pin.json").read_text())["corpus"]
    if hashlib.sha256(manifest_bytes).hexdigest() != pin["manifest.json"]:
        raise ValueError("corpus manifest differs from pin")
    manifest = json.loads(manifest_bytes)
    material = bytearray()
    names = []
    for entry in manifest["files"]:
        name = entry["path"]
        if name not in ("vectors.json", "expectations.json", "legacy-vectors.json"):
            raise ValueError("unexpected corpus inventory")
        data = (ROOT / name).read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        if (
            digest != entry["sha256"]
            or digest != pin[name]
            or len(data) != entry["size"]
        ):
            raise ValueError("authoritative corpus bytes changed")
        names.append(name)
        material.extend(f"{name}\0{digest}\0{len(data)}\n".encode())
    if (
        names != sorted(set(pin) - {"manifest.json"})
        or hashlib.sha256(material).hexdigest() != manifest["digest"]
    ):
        raise ValueError("corpus inventory or digest changed")
    legacy = (ROOT / "legacy-vectors.json").read_bytes()
    if (
        hashlib.sha256(legacy).hexdigest()
        != "4b8e07fd58687ef10b56bd34da890442aa925c67d142382f8c48feac04ba37dd"
    ):
        raise ValueError("historical corpus changed")
    vectors = json.loads((ROOT / "vectors.json").read_text())
    expectations = json.loads((ROOT / "expectations.json").read_text())
    names = [row["name"] for row in vectors]
    if (
        len(vectors) != 232
        or len(set(names)) != 232
        or vectors[:156] != json.loads(legacy)
        or names != [row["name"] for row in expectations]
    ):
        raise ValueError("missing, reordered or substituted corpus cases")
    return vectors


def render():
    build_vectors()
    output = (
        "// Generated by generate_vectors.py from the official corpus; do not edit.\n"
    )
    for name, filename in (
        ("titectVectorsJson", "vectors.json"),
        ("titectExpectationsJson", "expectations.json"),
    ):
        encoded = (
            json.dumps(
                json.loads((ROOT / filename).read_text()), ensure_ascii=True, indent=2
            )
            + "\n"
        )
        if "'''" in encoded:
            raise ValueError("corpus contains a Dart raw-string delimiter")
        output += f"const {name} = r'''{encoded}''';\n"
    return output


if __name__ == "__main__":
    path = ROOT / "vectors.g.dart"
    expected = render()
    if "--check" in sys.argv:
        if not path.exists() or path.read_text() != expected:
            raise SystemExit("Titect Dart corpus representation is stale")
    else:
        path.write_text(expected)
