name: dartitect_analyzer_plugin_fixture
publish_to: none

environment:
  sdk: ^3.13.0

dependencies:
  dartitect:
    path: dependencies/dartitect
  dartitect_dio:
    path: dependencies/dartitect_dio
  dartitect_flutter:
    path: dependencies/dartitect_flutter
  dartitect_observability:
    path: dependencies/dartitect_observability
  dartitect_sentry:
    path: dependencies/dartitect_sentry
  dio:
    path: dependencies/dio
  flutter:
    path: dependencies/flutter
  sentry: ^9.27.0
