name: dartitect_analyzer_plugin_fixture
publish_to: none

environment:
  sdk: ^3.13.0

dependencies:
  dartitect:
    path: dependencies/dartitect
  dartitect_flutter:
    path: dependencies/dartitect_flutter
  sentry: ^9.27.0
