// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages, public_member_api_docs, strict_raw_type
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart' as obx_int;
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'fixture_entity.dart';

export 'package:objectbox/objectbox.dart';

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8250576069256462807),
    name: 'FixtureEntity',
    lastPropertyId: const obx_int.IdUid(2, 2856689945209916456),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1566789464015561087),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2856689945209916456),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Opens the Store with this generated consumer model.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the generated ObjectBox model definition.
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 8250576069256462807),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FixtureEntity: obx_int.EntityDefinition<FixtureEntity>(
      model: _entities[0],
      toOneRelations: (FixtureEntity object) => [],
      toManyRelations: (FixtureEntity object) => {},
      getId: (FixtureEntity object) => object.id,
      setId: (FixtureEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FixtureEntity object, fb.Builder fbb) {
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final valueParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 6, '');
        return FixtureEntity(id: idParam, value: valueParam);
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// Generated query-property accessors for [FixtureEntity].
class FixtureEntity_ {
  /// See [FixtureEntity.id].
  static final id = obx.QueryIntegerProperty<FixtureEntity>(
    _entities[0].properties[0],
  );

  /// See [FixtureEntity.value].
  static final value = obx.QueryStringProperty<FixtureEntity>(
    _entities[0].properties[1],
  );
}
