// GENERATED CODE - DO NOT EDIT BY HAND.
// Generated by tool/generate_release_artifacts.dart.
// ignore_for_file: public_member_api_docs

abstract final class DartitectReleaseManifest {
  static const String workspaceVersion = '1.1.0-rc.1';
  static const String workspaceChannel = 'candidate';
  static const String candidateTag = 'v1.1.0-rc.1';
  static const bool candidateTagMaterialized = false;
  static const String distributedVersion = '1.0.0';
  static const String distributedTag = 'v1.0.0';
  static const String repository = 'https://github.com/ftr-tuta/dartitect.git';
  static const String tagPattern = 'v{{version}}';
  static const Map<String, String> packagePaths = <String, String>{
    'dartitect': 'packages/dartitect',
    'dartitect_geometry': 'packages/dartitect_geometry',
    'dartitect_locale_br': 'packages/dartitect_locale_br',
    'dartitect_privacy': 'packages/dartitect_privacy',
    'dartitect_isolates': 'packages/dartitect_isolates',
    'dartitect_jobs': 'packages/dartitect_jobs',
    'dartitect_media': 'packages/dartitect_media',
    'dartitect_modeling': 'packages/dartitect_modeling',
    'dartitect_resilience': 'packages/dartitect_resilience',
    'dartitect_sync': 'packages/dartitect_sync',
    'dartitect_observability': 'packages/dartitect_observability',
    'dartitect_devtools': 'packages/dartitect_devtools',
    'dartitect_flutter': 'packages/dartitect_flutter',
    'dartitect_transfer': 'packages/dartitect_transfer',
    'dartitect_flutter_testing': 'packages/dartitect_flutter_testing',
    'dartitect_modeling_analyzer': 'packages/dartitect_modeling_analyzer',
    'dartitect_sentry': 'packages/dartitect_sentry',
    'dartitect_workmanager': 'packages/dartitect_workmanager',
    'dartitect_dio': 'packages/dartitect_dio',
    'dartitect_drift': 'packages/dartitect_drift',
    'dartitect_objectbox': 'packages/dartitect_objectbox',
    'dartitect_testing': 'packages/dartitect_testing',
    'dartitect_cli': 'packages/dartitect_cli',
    'dartitect_lints': 'packages/dartitect_lints',
    'dartitect_mcp': 'packages/dartitect_mcp',
  };
  static const Map<String, String> workspacePackageVersions = <String, String>{
    'dartitect': '1.1.0-rc.1',
    'dartitect_geometry': '1.1.0-rc.1',
    'dartitect_locale_br': '1.1.0-rc.1',
    'dartitect_privacy': '1.1.0-rc.1',
    'dartitect_isolates': '1.1.0-rc.1',
    'dartitect_jobs': '1.1.0-rc.1',
    'dartitect_media': '1.1.0-rc.1',
    'dartitect_modeling': '1.1.0-rc.1',
    'dartitect_resilience': '1.1.0-rc.1',
    'dartitect_sync': '1.1.0-rc.1',
    'dartitect_observability': '1.1.0-rc.1',
    'dartitect_devtools': '1.1.0-rc.1',
    'dartitect_flutter': '1.1.0-rc.1',
    'dartitect_transfer': '1.1.0-rc.1',
    'dartitect_flutter_testing': '1.1.0-rc.1',
    'dartitect_modeling_analyzer': '1.1.0-rc.1',
    'dartitect_sentry': '1.1.0-rc.1',
    'dartitect_workmanager': '1.1.0-rc.1',
    'dartitect_dio': '1.1.0-rc.1',
    'dartitect_drift': '1.1.0-rc.1',
    'dartitect_objectbox': '1.1.0-rc.1',
    'dartitect_testing': '1.1.0-rc.1',
    'dartitect_cli': '1.1.0-rc.1',
    'dartitect_lints': '1.1.0-rc.1',
    'dartitect_mcp': '1.1.0-rc.1',
  };
}
