// GENERATED CODE - DO NOT EDIT BY HAND.
// Generated by tool/generate_release_artifacts.dart.
// ignore_for_file: public_member_api_docs

abstract final class DartitectReleaseManifest {
  static const String baselineVersion = '1.0.0-rc.9';
  static const String candidateTag = 'v1.0.0-rc.9';
  static const Map<String, String> compatibleRanges = <String, String>{
    'dartitect': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_geometry': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_locale_br': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_privacy': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_devtools': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_flutter': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_isolates': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_jobs': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_media': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_modeling': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_observability': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_resilience': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_transfer': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_modeling_analyzer': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_sentry': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_sync': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_workmanager': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_dio': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_drift': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_objectbox': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_testing': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_cli': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_lints': '>=1.0.0-rc.9 <1.0.0',
    'dartitect_mcp': '>=1.0.0-rc.9 <1.0.0',
  };
  static const Map<String, String> packageVersions = <String, String>{
    'dartitect': '1.0.0-rc.9',
    'dartitect_geometry': '1.0.0-rc.9',
    'dartitect_locale_br': '1.0.0-rc.9',
    'dartitect_privacy': '1.0.0-rc.9',
    'dartitect_devtools': '1.0.0-rc.9',
    'dartitect_flutter': '1.0.0-rc.9',
    'dartitect_isolates': '1.0.0-rc.9',
    'dartitect_jobs': '1.0.0-rc.9',
    'dartitect_media': '1.0.0-rc.9',
    'dartitect_modeling': '1.0.0-rc.9',
    'dartitect_observability': '1.0.0-rc.9',
    'dartitect_resilience': '1.0.0-rc.9',
    'dartitect_transfer': '1.0.0-rc.9',
    'dartitect_modeling_analyzer': '1.0.0-rc.9',
    'dartitect_sentry': '1.0.0-rc.9',
    'dartitect_sync': '1.0.0-rc.9',
    'dartitect_workmanager': '1.0.0-rc.9',
    'dartitect_dio': '1.0.0-rc.9',
    'dartitect_drift': '1.0.0-rc.9',
    'dartitect_objectbox': '1.0.0-rc.9',
    'dartitect_testing': '1.0.0-rc.9',
    'dartitect_cli': '1.0.0-rc.9',
    'dartitect_lints': '1.0.0-rc.9',
    'dartitect_mcp': '1.0.0-rc.9',
  };
}
