targets:
  $default:
    builders:
      drift_dev:
        generate_for:
          - lib/features/tasks/infrastructure/drift_task_database.dart
          - test/infrastructure/drift_audit_database.dart
