import 'dart:convert';
import 'dart:io';

import '../packages/dartitect_cli/lib/src/config/dartitect_config.dart';

Future<void> main(List<String> arguments) async {
  final root = File.fromUri(Platform.script).parent.parent.absolute;
  final releaseContract = _jsonObject(
    await File('${root.path}/tool/package_release_contract.json')
        .readAsString(),
  );
  final releasePackages = _jsonObject(releaseContract['packages']);
  final packages = <String, Object?>{};
  final packageDirectories = await Directory('${root.path}/packages')
      .list(followLinks: false)
      .where((entity) => entity is Directory)
      .cast<Directory>()
      .toList();
  packageDirectories.sort((left, right) => left.path.compareTo(right.path));
  for (final directory in packageDirectories) {
    final pubspec = File('${directory.path}/pubspec.yaml');
    if (!await pubspec.exists()) continue;
    final source = await pubspec.readAsString();
    final name = _yamlField(source, 'name');
    final docs = _jsonObject(releasePackages[name]);
    final readme = await File('${directory.path}/README.md').readAsString();
    packages[name] = <String, Object?>{
      'version': _yamlField(source, 'version'),
      'description': _yamlField(source, 'description'),
      'documentation': _purpose(readme),
      'platforms': docs['platforms'],
      'stability': docs['stability'],
    };
  }
  if (packages.length != releasePackages.length) {
    throw StateError(
      'Package platform documentation and workspace package count differ.',
    );
  }

  final diagnosticDocument = _jsonObject(
    await File('${root.path}/docs/mcp/diagnostics.json').readAsString(),
  );
  final diagnostics = _jsonObject(diagnosticDocument['diagnostics']);
  final guides = <String, Object?>{};
  final guideFiles = await Directory('${root.path}/docs/guides')
      .list(followLinks: false)
      .where((entity) => entity is File && entity.path.endsWith('.md'))
      .cast<File>()
      .toList();
  guideFiles.sort((left, right) => left.path.compareTo(right.path));
  for (final file in guideFiles) {
    final name = _basename(file.path)
        .substring(0, _basename(file.path).length - '.md'.length);
    guides[name] = await file.readAsString();
  }

  final config = DartitectConfig().toJson();
  final snapshot = await File('${root.path}/tool/api_surface.snapshot.json')
      .readAsString();
  final payload = <String, Object?>{
    'packages': packages,
    'diagnostics': diagnostics,
    'guides': guides,
    'configV2': config,
    'apiSnapshotHash': _hash(snapshot),
  };
  final encoded = const JsonEncoder.withIndent('  ').convert(payload);
  final generated =
      """// GENERATED CODE - DO NOT EDIT BY HAND.
// Generated by tool/generate_mcp_catalog.dart from package metadata, public
// guides, config v2, diagnostics, and the reviewed API snapshot.

import 'dart:convert';

/// Generated MCP package, diagnostic, guide, config, and API-snapshot data.
abstract final class DartitectGeneratedCatalog {
  /// Package metadata sourced from each pubspec/README and platform docs.
  static final Map<String, Map<String, Object?>> packages = _nestedObjectMap(
    _payload['packages'],
  );

  /// Stable diagnostic explanations sourced from public diagnostic docs.
  static final Map<String, Map<String, String>> diagnostics = _nestedStringMap(
    _payload['diagnostics'],
  );

  /// Canonical English public guides keyed by slug.
  static final Map<String, String> guides =
      (_payload['guides']! as Map<String, Object?>).cast<String, String>();

  /// Credential-free config v2 example sourced from stable CLI defaults.
  static final Map<String, Object?> configV2 =
      _payload['configV2']! as Map<String, Object?>;

  /// FNV-1a hash of the reviewed public API snapshot.
  static final String apiSnapshotHash = _payload['apiSnapshotHash']! as String;

  static final Map<String, Object?> _payload =
      (jsonDecode(_source) as Map<String, Object?>);

  static Map<String, Map<String, Object?>> _nestedObjectMap(Object? value) =>
      (value! as Map<String, Object?>).map(
        (key, item) => MapEntry(key, item! as Map<String, Object?>),
      );

  static Map<String, Map<String, String>> _nestedStringMap(Object? value) =>
      (value! as Map<String, Object?>).map(
        (key, item) => MapEntry(
          key,
          (item! as Map<String, Object?>).cast<String, String>(),
        ),
      );

  static const String _source = r'''$encoded''';
}
""";
  final output = File(
    '${root.path}/packages/dartitect_mcp/lib/src/catalog/generated_catalog.dart',
  );
  if (arguments.contains('--check')) {
    if (!await output.exists() || await output.readAsString() != generated) {
      stderr.writeln(
        'MCP catalog is stale; run dart run tool/generate_mcp_catalog.dart.',
      );
      exitCode = 1;
      return;
    }
    stdout.writeln(
      'MCP catalog is current: ${packages.length} packages, '
      '${diagnostics.length} diagnostics, ${guides.length} guides.',
    );
    return;
  }
  await output.writeAsString(generated, flush: true);
  stdout.writeln('Generated MCP catalog.');
}

Map<String, Object?> _jsonObject(Object? source) {
  final value = source is String ? jsonDecode(source) : source;
  if (value is! Map<String, Object?>) {
    throw const FormatException('Expected a JSON object.');
  }
  return value;
}

String _yamlField(String source, String name) {
  final pattern = '^${RegExp.escape(name)}:\\s*(.+?)\\s*\$';
  final match = RegExp(pattern, multiLine: true).firstMatch(source);
  if (match == null) throw FormatException('Missing $name in pubspec.');
  return match.group(1)!;
}

String _purpose(String readme) {
  final lines = readme.split(RegExp(r'\r?\n'));
  final heading = lines.indexWhere((line) => line == '## Purpose');
  if (heading < 0)
    throw const FormatException('README has no Purpose heading.');
  final result = <String>[];
  for (final line in lines.skip(heading + 1)) {
    if (line.startsWith('## ')) break;
    if (line.trim().isNotEmpty) result.add(line.trim());
  }
  return result.join(' ');
}

String _hash(String content) {
  var hash = 0x811c9dc5;
  for (final byte in utf8.encode(content)) {
    hash ^= byte;
    hash = (hash * 0x01000193) & 0xffffffff;
  }
  return hash.toRadixString(16).padLeft(8, '0');
}

String _basename(String path) =>
    path.split(Platform.pathSeparator).where((part) => part.isNotEmpty).last;
