import 'dart:convert';
import 'dart:io';

/// Generates or verifies every release artifact derived from the release contract.
Future<void> main(List<String> arguments) async {
  final check = arguments.contains('--check');
  if (arguments.any((argument) => argument != '--check')) {
    stderr.writeln(
      'Usage: dart run tool/generate_release_artifacts.dart [--check]',
    );
    exitCode = 2;
    return;
  }
  final root = File.fromUri(Platform.script).parent.parent.absolute;
  final contract = _object(
    jsonDecode(
      await File('${root.path}/tool/package_release_contract.json')
          .readAsString(),
    ),
  );
  final packages = _object(contract['packages']);
  final cohorts = _object(contract['publicationCohorts']);
  final compatibility = _object(contract['compatibility']);
  final order = _strings(contract['publicationOrder']);
  final layers = (contract['publicationLayers']! as List<Object?>)
      .map(_strings)
      .toList();
  final outputs = <String, String>{
    'VERSIONING.adoc': _versioning(contract, cohorts, layers),
    'docs/mcp/package-platforms.json': _platforms(packages),
    'docs/release/package-cohorts.adoc': _cohortDocument(contract, cohorts),
    'packages/dartitect_cli/lib/src/release/generated_release_manifest.dart':
        _dartManifest(contract, packages, compatibility, order),
  };
  final stale = <String>[];
  for (final entry in outputs.entries) {
    final file = File('${root.path}/${entry.key}');
    if (check) {
      if (!await file.exists() || await file.readAsString() != entry.value) {
        stale.add(entry.key);
      }
    } else {
      await file.parent.create(recursive: true);
      await file.writeAsString(entry.value, flush: true);
    }
  }
  if (stale.isNotEmpty) {
    stderr.writeln(
      'Release artifacts are stale: ${stale.join(', ')}. Run '
      '`dart run tool/generate_release_artifacts.dart`.',
    );
    exitCode = 1;
    return;
  }

  final commands = <(String, List<String>)>[
    (
      'tool/check_sdk_inventory.dart',
      check ? const <String>[] : const <String>['--update'],
    ),
    (
      'tool/generate_mcp_catalog.dart',
      check ? const <String>['--check'] : const <String>[],
    ),
    (
      'tool/generate_supply_chain.dart',
      check ? const <String>['--check'] : const <String>[],
    ),
  ];
  for (final command in commands) {
    final result = await Process.run(Platform.resolvedExecutable, <String>[
      command.$1,
      ...command.$2,
    ], workingDirectory: root.path);
    stdout.write(result.stdout);
    stderr.write(result.stderr);
    if (result.exitCode != 0) {
      exitCode = result.exitCode;
      return;
    }
  }
  stdout.writeln(
    '${check ? 'Checked' : 'Generated'} release artifacts from '
    'tool/package_release_contract.json.',
  );
}

String _versioning(
  Map<String, Object?> contract,
  Map<String, Object?> cohorts,
  List<List<String>> layers,
) {
  final compatibility = _object(contract['compatibility']);
  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED BY tool/generate_release_artifacts.dart; DO NOT EDIT.',
    )
    ..writeln('= Versioning and publication policy')
    ..writeln()
    ..writeln('== RC8 baseline and post-1.0 independence')
    ..writeln()
    ..writeln(
      'All ${contract['packageCount']} packages start at '
      '+${contract['baselineVersion']}+. RC7 is intentionally skipped. The '
      'candidate tag is +${contract['candidateTag']}+ and is not materialized '
      'by this source delivery.',
    )
    ..writeln()
    ..writeln(
      'During RC8, internal dependencies use '
      '+${compatibility['defaultRange']}+. After 1.0, packages may receive '
      'independent patches; compatibility is determined by the generated '
      'package manifest and consumer lockfile, never global version equality. '
      'The default stable range is +${compatibility['stableDefaultRange']}+.',
    )
    ..writeln()
    ..writeln('== Publication cohorts')
    ..writeln();
  for (final entry in cohorts.entries) {
    buffer.writeln(
      '* +${entry.key}+: ${_strings(entry.value).map((name) => '+$name+').join(', ')}.',
    );
  }
  buffer
    ..writeln()
    ..writeln('== Publication DAG')
    ..writeln();
  for (var index = 0; index < layers.length; index += 1) {
    buffer.writeln(
      '. Layer $index: ${layers[index].map((name) => '+$name+').join(', ')}.',
    );
  }
  buffer
    ..writeln()
    ..writeln('== Reproducibility and authorization')
    ..writeln()
    ..writeln(
      'Every artifact is tied to one clean source SHA and canonical SHA-256 '
      'digests. Path dependencies and dependency overrides are forbidden in '
      'publishable archives. Publication stops on the first failure and may '
      'resume only with identical source and digests.',
    )
    ..writeln()
    ..writeln(
      'Green gates do not authorize a tag, GitHub Release, or pub.dev '
      'publication. Those actions require a separate post-merge authorization.',
    );
  return buffer.toString();
}

String _platforms(Map<String, Object?> packages) {
  final sorted = packages.keys.toList()..sort();
  return '${const JsonEncoder.withIndent('  ').convert(<String, Object?>{
    'schemaVersion': 2,
    'source': 'tool/package_release_contract.json',
    'packages': <String, Object?>{
      for (final name in sorted) name: <String, Object?>{'platforms': _object(packages[name])['platforms'], 'stability': _object(packages[name])['stability']},
    },
  })}\n';
}

String _cohortDocument(
  Map<String, Object?> contract,
  Map<String, Object?> cohorts,
) {
  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED BY tool/generate_release_artifacts.dart; DO NOT EDIT.',
    )
    ..writeln('= RC8 package cohorts')
    ..writeln()
    ..writeln('Baseline:: +${contract['baselineVersion']}+')
    ..writeln(
      'Candidate tag:: +${contract['candidateTag']}+ (not materialized)',
    )
    ..writeln('Package count:: ${contract['packageCount']}')
    ..writeln('Public entrypoint count:: ${contract['publicEntrypointCount']}')
    ..writeln()
    ..writeln('[cols="1,3",options="header"]')
    ..writeln('|===')
    ..writeln('| Cohort | Packages');
  for (final entry in cohorts.entries) {
    buffer
      ..writeln('| ${entry.key}')
      ..writeln(
        '| ${_strings(entry.value).map((name) => '+$name+').join(', ')}',
      );
  }
  buffer.writeln('|===');
  return buffer.toString();
}

String _dartManifest(
  Map<String, Object?> contract,
  Map<String, Object?> packages,
  Map<String, Object?> compatibility,
  List<String> order,
) {
  final overrides = _object(compatibility['packageRanges']);
  String range(String package) =>
      overrides[package] as String? ?? compatibility['defaultRange']! as String;
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT EDIT BY HAND.')
    ..writeln('// Generated by tool/generate_release_artifacts.dart.')
    ..writeln('// ignore_for_file: public_member_api_docs')
    ..writeln()
    ..writeln('abstract final class DartitectReleaseManifest {')
    ..writeln(
      "  static const String baselineVersion = '${contract['baselineVersion']}';",
    )
    ..writeln(
      "  static const String candidateTag = '${contract['candidateTag']}';",
    )
    ..writeln(
      '  static const Map<String, String> compatibleRanges = <String, String>{',
    );
  for (final name in order) {
    buffer.writeln("    '$name': '${range(name)}',");
  }
  buffer
    ..writeln('  };')
    ..writeln(
      '  static const Map<String, String> packageVersions = <String, String>{',
    );
  for (final name in order) {
    buffer.writeln("    '$name': '${_object(packages[name])['version']}',");
  }
  buffer
    ..writeln('  };')
    ..writeln('}');
  return buffer.toString();
}

Map<String, Object?> _object(Object? value) {
  if (value is! Map<String, Object?>) {
    throw const FormatException('Expected JSON object.');
  }
  return value;
}

List<String> _strings(Object? value) {
  if (value is! List<Object?> || value.any((item) => item is! String)) {
    throw const FormatException('Expected JSON string list.');
  }
  return value.cast<String>();
}
