import 'dart:convert';
import 'dart:io';

import 'release_contract.dart';

/// Generates or verifies every artifact derived from the release contract.
Future<void> main(List<String> arguments) async {
  final check = arguments.contains('--check');
  if (arguments.any((argument) => argument != '--check')) {
    stderr.writeln(
      'Usage: dart run tool/generate_release_artifacts.dart [--check]',
    );
    exitCode = 2;
    return;
  }
  final root = File.fromUri(Platform.script).parent.parent.absolute;
  final cohorts = ReleaseCohortContract.read(root);
  final contract = _object(
    jsonDecode(
      await File('${root.path}/tool/package_release_contract.json')
          .readAsString(),
    ),
  );
  final packages = _object(contract['packages']);
  final paths = _object(contract['packagePaths']);
  final order = _strings(contract['dependencyOrder']);
  final outputs = <String, String>{
    'VERSIONING.adoc': _versioning(contract, cohorts),
    'docs/mcp/package-platforms.json': _platforms(packages),
    'docs/release/package-cohorts.adoc': _cohortDocument(
      contract,
      cohorts,
      order,
    ),
    'packages/dartitect_cli/lib/src/release/generated_release_manifest.dart':
        _dartManifest(cohorts, packages, paths, order),
  };
  final stale = <String>[];
  for (final entry in outputs.entries) {
    final file = File('${root.path}/${entry.key}');
    if (check) {
      if (!await file.exists() || await file.readAsString() != entry.value) {
        stale.add(entry.key);
      }
    } else {
      await file.parent.create(recursive: true);
      await file.writeAsString(entry.value, flush: true);
    }
  }
  if (stale.isNotEmpty) {
    stderr.writeln(
      'Release artifacts are stale: ${stale.join(', ')}. Run '
      '`dart run tool/generate_release_artifacts.dart`.',
    );
    exitCode = 1;
    return;
  }

  final commands = <(String, List<String>)>[
    (
      'tool/check_sdk_inventory.dart',
      check ? const <String>[] : const <String>['--update'],
    ),
    (
      'tool/generate_mcp_catalog.dart',
      check ? const <String>['--check'] : const <String>[],
    ),
    (
      'tool/generate_supply_chain.dart',
      check ? const <String>['--check'] : const <String>[],
    ),
  ];
  for (final command in commands) {
    final result = await Process.run(Platform.resolvedExecutable, <String>[
      command.$1,
      ...command.$2,
    ], workingDirectory: root.path);
    stdout.write(result.stdout);
    stderr.write(result.stderr);
    if (result.exitCode != 0) {
      exitCode = result.exitCode;
      return;
    }
  }
  stdout.writeln(
    '${check ? 'Checked' : 'Generated'} release artifacts from '
    'tool/package_release_contract.json.',
  );
}

String _versioning(
  Map<String, Object?> contract,
  ReleaseCohortContract cohorts,
) {
  final distribution = _object(contract['distribution']);
  return '''// GENERATED BY tool/generate_release_artifacts.dart; DO NOT EDIT.
= Versioning and GitHub-only distribution policy

== Permanent lockstep

All ${contract['packageCount']} packages in the development workspace share +${cohorts.workspace.version}+. Its channel is +${cohorts.workspace.channel}+ and its derivable tag is +${cohorts.workspace.tag}+; that tag is ${cohorts.workspace.tagMaterialized ? 'materialized' : 'not materialized'}.

The latest stable distribution recorded in this source is +${cohorts.distributed.version}+ at the immutable +${cohorts.distributed.tag}+ tag. ${cohorts.workspace.tagMaterialized ? 'The stable workspace and recorded distribution use the same materialized tag.' : 'The prepared workspace does not change this publication record. Its eventual publication and exact source are recorded by the immutable GitHub Release, checksummed assets, and attestation.'}

Independent package patch ranges and registry publication are not supported. Internal Dartitect dependencies use the canonical Git descriptor with +tag_pattern: 'v{{version}}'+ and the same exact version as the release tag.

== Distribution

The only supported Dartitect distribution is the immutable GitHub Release at ${distribution['repository']}. External dependencies continue to resolve from their normal registries. Every Dartitect package declares +publish_to: none+.

== Reproducibility and authorization

Every artifact is tied to one clean +main+ source SHA and canonical SHA-256 digests. Dartitect path dependencies and dependency overrides are forbidden in consumer evidence; workspace resolution is used only inside this development repository.

Green gates do not authorize a tag or GitHub Release. The manual +Release+ workflow requires the exact successful +main+ CI run and its unexpired +actions-readiness-v1+ artifact before any write.
''';
}

String _platforms(Map<String, Object?> packages) {
  final sorted = packages.keys.toList()..sort();
  return '${const JsonEncoder.withIndent('  ').convert(<String, Object?>{
    'schemaVersion': 3,
    'source': 'tool/package_release_contract.json',
    'packages': <String, Object?>{
      for (final name in sorted) name: <String, Object?>{'platforms': _object(packages[name])['platforms'], 'stability': _object(packages[name])['stability']},
    },
  })}\n';
}

String _cohortDocument(
  Map<String, Object?> contract,
  ReleaseCohortContract cohorts,
  List<String> order,
) {
  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED BY tool/generate_release_artifacts.dart; DO NOT EDIT.',
    )
    ..writeln('= ${cohorts.workspace.version} lockstep workspace cohort')
    ..writeln()
    ..writeln('Workspace channel:: +${cohorts.workspace.channel}+')
    ..writeln('Derivable workspace tag:: +${cohorts.workspace.tag}+')
    ..writeln(
      'Workspace tag materialized:: +${cohorts.workspace.tagMaterialized}+',
    )
    ..writeln('Stable distribution:: +${cohorts.distributed.tag}+')
    ..writeln('Package count:: ${contract['packageCount']}')
    ..writeln('Public entrypoint count:: ${contract['publicEntrypointCount']}')
    ..writeln()
    ..writeln('== Dependency order')
    ..writeln();
  for (var index = 0; index < order.length; index += 1) {
    buffer.writeln('. +${order[index]}+');
  }
  return buffer.toString();
}

String _dartManifest(
  ReleaseCohortContract cohorts,
  Map<String, Object?> packages,
  Map<String, Object?> paths,
  List<String> order,
) {
  final dependency = cohorts.distributedDependency;
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT EDIT BY HAND.')
    ..writeln('// Generated by tool/generate_release_artifacts.dart.')
    ..writeln('// ignore_for_file: public_member_api_docs')
    ..writeln()
    ..writeln('abstract final class DartitectReleaseManifest {')
    ..writeln(
      "  static const String workspaceVersion = '${cohorts.workspace.version}';",
    )
    ..writeln(
      "  static const String workspaceChannel = '${cohorts.workspace.channel}';",
    )
    ..writeln(
      "  static const String candidateTag = '${cohorts.workspace.tag}';",
    )
    ..writeln(
      '  static const bool candidateTagMaterialized = '
      '${cohorts.workspace.tagMaterialized};',
    )
    ..writeln(
      "  static const String distributedVersion = '${cohorts.distributed.version}';",
    )
    ..writeln(
      "  static const String distributedTag = '${cohorts.distributed.tag}';",
    )
    ..writeln(
      "  static const String consumptionVersion = '${cohorts.workspace.isPrerelease ? cohorts.distributed.version : cohorts.workspace.version}';",
    )
    ..writeln(
      "  static const String consumptionTag = 'v${cohorts.workspace.isPrerelease ? cohorts.distributed.version : cohorts.workspace.version}';",
    )
    ..writeln("  static const String repository = '${dependency['url']}';")
    ..writeln(
      "  static const String tagPattern = '${dependency['tagPattern']}';",
    )
    ..writeln(
      '  static const Map<String, String> packagePaths = <String, String>{',
    );
  for (final name in order) {
    buffer.writeln("    '$name': '${paths[name]}',");
  }
  buffer
    ..writeln('  };')
    ..writeln(
      '  static const Map<String, String> workspacePackageVersions = '
      '<String, String>{',
    );
  for (final name in order) {
    buffer.writeln("    '$name': '${_object(packages[name])['version']}',");
  }
  buffer
    ..writeln('  };')
    ..writeln('}');
  return buffer.toString();
}

Map<String, Object?> _object(Object? value) {
  if (value is! Map<String, Object?>) {
    throw const FormatException('Expected JSON object.');
  }
  return value;
}

List<String> _strings(Object? value) {
  if (value is! List<Object?> || value.any((item) => item is! String)) {
    throw const FormatException('Expected JSON string list.');
  }
  return value.cast<String>();
}
