import 'dart:convert';
import 'dart:io';

import 'package:dartitect/dartitect.dart' show FeatureProfile;

import '../config/dartitect_config.dart';
import 'consumer_tax_analyzer.dart';

/// One consumer-tax ratchet violation.
final class ConsumerTaxFinding {
  /// Creates a path-safe structural or budget finding.
  const ConsumerTaxFinding({
    required this.code,
    required this.message,
    this.path,
    this.evidence,
  });

  /// Stable `DT40xx` code.
  final String code;

  /// Payload-free remediation-oriented summary.
  final String message;

  /// Project-relative path when one file caused the finding.
  final String? path;

  /// Bounded structural evidence with no source bytes.
  final String? evidence;

  /// Stable JSON representation.
  Map<String, Object?> toJson() => <String, Object?>{
    'code': code,
    'message': message,
    if (path != null) 'path': path,
    if (evidence != null) 'evidence': evidence,
  };
}

/// Read-only consumer-tax metrics, ratchets, and findings.
final class ConsumerTaxReport {
  /// Creates a complete deterministic report.
  const ConsumerTaxReport({
    required this.profile,
    required this.metrics,
    required this.budgets,
    required this.capabilityOptIns,
    required this.requiredSymbols,
    required this.unusedDependencies,
    required this.findings,
    required this.architectureTax,
    required this.generatedTax,
    required this.testTax,
    required this.productCode,
    required this.diagnostics,
  });

  /// Report schema version.
  static const int schemaVersion = 2;

  /// Most capable declared feature profile, or `local` for an empty shell.
  final String profile;

  /// Observed counts and optional recorded analysis/build timings.
  final Map<String, Object?> metrics;

  /// Active ratchets for [profile].
  final Map<String, int> budgets;

  /// Explicit config v2 capability selections.
  final Map<String, bool> capabilityOptIns;

  /// Sorted public-looking symbols referenced from Dartitect-importing files.
  final List<String> requiredSymbols;

  /// Direct runtime dependencies with no Dart import in the project.
  final List<String> unusedDependencies;

  /// Blocking structural and ratchet findings.
  final List<ConsumerTaxFinding> findings;

  /// Consumer-authored structural plumbing; its mandatory budget is zero.
  final Map<String, Object?> architectureTax;

  /// Manifest-owned output size and its additive capability budget.
  final Map<String, Object?> generatedTax;

  /// Architecture-test and structural-fake observations.
  final Map<String, Object?> testTax;

  /// Domain and UI size, reported but never ratcheted.
  final Map<String, Object?> productCode;

  /// Analyzer-mode and timing-comparability diagnostics.
  final List<String> diagnostics;

  /// Whether every active ratchet passed.
  bool get isCompliant => findings.isEmpty;

  /// Process exit status.
  int get exitCode => isCompliant ? 0 : 1;

  /// Stable machine-readable report.
  Map<String, Object?> toJson() => <String, Object?>{
    'schemaVersion': schemaVersion,
    'command': 'inspect consumer-tax',
    'profile': profile,
    'compliant': isCompliant,
    'metrics': metrics,
    'budgets': budgets,
    'capabilityOptIns': capabilityOptIns,
    'requiredSymbols': requiredSymbols,
    'unusedDependencies': unusedDependencies,
    'architectureTax': architectureTax,
    'generatedTax': generatedTax,
    'testTax': testTax,
    'productCode': productCode,
    'diagnostics': diagnostics,
    'findings': findings.map((finding) => finding.toJson()).toList(),
    'exitCode': exitCode,
  };
}

/// Measures manual structural plumbing and minimal capability closure.
final class ConsumerTaxInspector {
  /// Creates an inspector confined to [root].
  ConsumerTaxInspector(Directory root) : root = root.absolute;

  /// Consumer project boundary.
  final Directory root;

  /// Inspects source, config, dependencies, generated bytes, and recorded time.
  Future<ConsumerTaxReport> inspect() async {
    final timer = Stopwatch()..start();
    final configFile = File(_join(root.path, 'dartitect.json'));
    final config = await configFile.exists()
        ? await DartitectConfig.load(configFile)
        : DartitectConfig(features: DartitectFeaturesConfig());
    final profile = _effectiveProfile(config);
    final files = await _dartFiles();
    final semanticFacts = await ConsumerTaxSemanticAnalyzer(root)
        .analyze(files);
    final factsByPath = <String, ConsumerTaxFileFacts>{
      for (final facts in semanticFacts) facts.path: facts,
    };
    final importedPackages = <String>{};
    final requiredSymbols = <String>{};
    final findings = <ConsumerTaxFinding>[];
    final diagnostics = <String>[];
    var sourceFiles = 0;
    var sourceLines = 0;
    var testFiles = 0;
    var testLines = 0;
    var generatedFiles = 0;
    var generatedBytes = 0;
    var manualListeners = 0;
    var manualLifecycle = 0;
    var cancellationSources = 0;
    var providerWiring = 0;
    var manualPlumbing = 0;
    var generatedOnceStructuralFiles = 0;
    var testTaxCount = 0;
    var resolvedFiles = 0;
    var syntacticFiles = 0;

    for (final file in files) {
      final relative = _relative(file.path);
      final source = await file.readAsString();
      final generated = _isGenerated(relative, source, config);
      final facts = factsByPath[relative]!;
      importedPackages.addAll(facts.importedPackages);
      if (generated) {
        generatedFiles += 1;
        generatedBytes += await file.length();
        continue;
      }
      if (facts.resolved) {
        resolvedFiles += 1;
      } else {
        syntacticFiles += 1;
      }
      requiredSymbols.addAll(facts.dartitectSymbols);
      manualListeners += facts.listeners;
      manualLifecycle += facts.lifecycleCalls;
      cancellationSources += facts.cancellationSources;
      providerWiring += facts.providerImports;
      if (!facts.test) manualPlumbing += facts.architecturePlumbing;
      testTaxCount += facts.testTax;
      for (final semantic in facts.findings) {
        findings.add(
          ConsumerTaxFinding(
            code: semantic.code,
            message: semantic.message,
            path: relative,
            evidence: semantic.evidence,
          ),
        );
      }
      generatedOnceStructuralFiles += facts.findings
          .where((finding) => finding.code == 'DT4004')
          .length;
      final lines = '\n'.allMatches(source).length + 1;
      if (facts.test) {
        testFiles += 1;
        testLines += lines;
      } else {
        sourceFiles += 1;
        sourceLines += lines;
      }
    }
    diagnostics.add(
      resolvedFiles > 0
          ? 'analyzer: resolved identities used for $resolvedFiles files'
          : 'analyzer: syntactic AST fallback; package resolution unavailable',
    );
    if (syntacticFiles > 0 && resolvedFiles > 0) {
      diagnostics.add(
        'analyzer: syntactic AST fallback used for $syntacticFiles files',
      );
    }

    final directDependencies = await _directDependencies();
    final unusedDependencies =
        directDependencies
            .where(
              (dependency) =>
                  dependency != 'flutter' &&
                  dependency.startsWith('dartitect') &&
                  !importedPackages.contains(dependency),
            )
            .toList()
          ..sort();
    for (final dependency in unusedDependencies) {
      findings.add(
        ConsumerTaxFinding(
          code: 'DT4005',
          message: 'A direct Dartitect dependency is unused.',
          path: 'pubspec.yaml',
          evidence: dependency,
        ),
      );
    }
    final optIns = _capabilityOptIns(config);
    final resolved = await _resolvedDependencies(directDependencies);
    for (final capability in _capabilityPackages.entries) {
      if (optIns[capability.key] == true) continue;
      final unexpected = capability.value.intersection(resolved).toList()
        ..sort();
      for (final dependency in unexpected) {
        findings.add(
          ConsumerTaxFinding(
            code: 'DT4006',
            message:
                'A capability dependency is resolved without config opt-in.',
            path: 'pubspec.yaml',
            evidence: '${capability.key}: $dependency',
          ),
        );
      }
    }

    final recorded = await _recordedPerformance();
    diagnostics.add(recorded.diagnostic);
    if (recorded.comparable) {
      for (final regression in recorded.regressions) {
        findings.add(
          ConsumerTaxFinding(
            code: 'DT4008',
            message: 'Same-runner CI timing regressed by more than 20%.',
            evidence: regression,
          ),
        );
      }
    }
    timer.stop();
    final generatedBudget = _generatedBudget(config);
    final budget = <String, int>{
      'manualPlumbing': 0,
      'generatedBytes': generatedBudget.totalBytes,
      'testTax': 0,
    };
    final metrics = <String, Object?>{
      'manualPlumbing': manualPlumbing,
      'manualListeners': manualListeners,
      'manualLifecycle': manualLifecycle,
      'cancellationSources': cancellationSources,
      'providerSpecificWiring': providerWiring,
      'requiredSymbolCount': requiredSymbols.length,
      'generatedOnceStructuralFiles': generatedOnceStructuralFiles,
      'unusedDependencyCount': unusedDependencies.length,
      'directDependencyCount': directDependencies.length,
      'sourceFiles': sourceFiles,
      'sourceLines': sourceLines,
      'testFiles': testFiles,
      'testLines': testLines,
      'generatedFiles': generatedFiles,
      'generatedBytes': generatedBytes,
      'inspectionMillis': timer.elapsedMilliseconds,
      'analysisMillis': recorded.currentAnalysisMillis,
      'buildMillis': recorded.currentBuildMillis,
      'testTax': testTaxCount,
    };
    if (generatedBytes > generatedBudget.totalBytes) {
      findings.add(
        ConsumerTaxFinding(
          code: 'DT4007',
          message: 'Generated output exceeded its additive graph budget.',
          evidence: '$generatedBytes > ${generatedBudget.totalBytes}',
        ),
      );
    }
    findings.sort((left, right) {
      final code = left.code.compareTo(right.code);
      return code != 0 ? code : '${left.path}'.compareTo('${right.path}');
    });
    final symbols = requiredSymbols.toList()..sort();
    return ConsumerTaxReport(
      profile: profile,
      metrics: Map<String, Object?>.unmodifiable(metrics),
      budgets: Map<String, int>.unmodifiable(budget),
      capabilityOptIns: Map<String, bool>.unmodifiable(optIns),
      requiredSymbols: List<String>.unmodifiable(symbols),
      unusedDependencies: List<String>.unmodifiable(unusedDependencies),
      findings: List<ConsumerTaxFinding>.unmodifiable(findings),
      architectureTax: Map<String, Object?>.unmodifiable(<String, Object?>{
        'observed': manualPlumbing,
        'limit': 0,
        'analyzerResolvedFiles': resolvedFiles,
        'syntacticFallbackFiles': syntacticFiles,
      }),
      generatedTax: Map<String, Object?>.unmodifiable(<String, Object?>{
        'observedFiles': generatedFiles,
        'observedBytes': generatedBytes,
        'budgetBytes': generatedBudget.totalBytes,
        'axes': generatedBudget.axes,
      }),
      testTax: Map<String, Object?>.unmodifiable(<String, Object?>{
        'observed': testTaxCount,
        'limit': 0,
        'files': testFiles,
        'lines': testLines,
      }),
      productCode: Map<String, Object?>.unmodifiable(<String, Object?>{
        'files': sourceFiles,
        'lines': sourceLines,
        'blocking': false,
      }),
      diagnostics: List<String>.unmodifiable(diagnostics),
    );
  }

  Future<List<File>> _dartFiles() async {
    final output = <File>[];
    for (final directory in <Directory>[
      Directory(_join(root.path, 'lib')),
      Directory(_join(root.path, 'test')),
    ]) {
      if (!await directory.exists()) continue;
      await for (final entity in directory.list(
        recursive: true,
        followLinks: false,
      )) {
        if (entity is File && entity.path.endsWith('.dart')) output.add(entity);
      }
    }
    final packages = Directory(_join(root.path, 'packages'));
    if (await packages.exists()) {
      await for (final entity in packages.list(followLinks: false)) {
        if (entity is! Directory) continue;
        final lib = Directory(_join(entity.path, 'lib'));
        final test = Directory(_join(entity.path, 'test'));
        for (final source in <Directory>[lib, test]) {
          if (!await source.exists()) continue;
          await for (final child in source.list(
            recursive: true,
            followLinks: false,
          )) {
            if (child is File && child.path.endsWith('.dart'))
              output.add(child);
          }
        }
      }
    }
    output.sort((left, right) => left.path.compareTo(right.path));
    return output;
  }

  Future<Set<String>> _directDependencies() async {
    final pubspec = File(_join(root.path, 'pubspec.yaml'));
    if (!await pubspec.exists()) return <String>{};
    final output = <String>{};
    var dependencies = false;
    for (final line in await pubspec.readAsLines()) {
      if (line == 'dependencies:') {
        dependencies = true;
        continue;
      }
      if (dependencies && line.isNotEmpty && !line.startsWith(' ')) break;
      final match = dependencies
          ? RegExp(r'^  ([a-zA-Z][a-zA-Z0-9_]*):').firstMatch(line)
          : null;
      if (match != null) output.add(match.group(1)!);
    }
    return output;
  }

  Future<Set<String>> _resolvedDependencies(Set<String> direct) async {
    final lock = File(_join(root.path, 'pubspec.lock'));
    if (!await lock.exists()) return direct;
    final output = <String>{};
    var packages = false;
    for (final line in await lock.readAsLines()) {
      if (line == 'packages:') {
        packages = true;
        continue;
      }
      if (packages && line.isNotEmpty && !line.startsWith(' ')) break;
      final match = packages
          ? RegExp(r'^  ([a-zA-Z][a-zA-Z0-9_]*):$').firstMatch(line)
          : null;
      if (match != null) output.add(match.group(1)!);
    }
    return output.isEmpty ? direct : output;
  }

  Future<_RecordedPerformance> _recordedPerformance() async {
    final file = File(_join(root.path, '.dartitect/consumer-tax-metrics.json'));
    if (!await file.exists()) {
      return const _RecordedPerformance(
        diagnostic:
            'timings: no CI evidence recorded; no timing ratchet applied',
      );
    }
    final decoded = jsonDecode(await file.readAsString());
    if (decoded is! Map<String, Object?>) {
      throw const FormatException('Invalid consumer-tax performance metrics.');
    }
    if (decoded['schemaVersion'] == 1) {
      return _RecordedPerformance(
        currentAnalysisMillis: decoded['analysisMillis'] as int?,
        currentBuildMillis: decoded['buildMillis'] as int?,
        diagnostic:
            'timings: legacy schema 1 evidence observed but not ratcheted',
      );
    }
    if (decoded['schemaVersion'] != 2 ||
        decoded['runner'] is! String ||
        decoded['baseline'] is! Map<String, Object?> ||
        decoded['current'] is! Map<String, Object?>) {
      throw const FormatException('Invalid consumer-tax performance metrics.');
    }
    final baseline = decoded['baseline']! as Map<String, Object?>;
    final current = decoded['current']! as Map<String, Object?>;
    final baselineAnalysis = baseline['analysisMillis'];
    final baselineBuild = baseline['buildMillis'];
    final currentAnalysis = current['analysisMillis'];
    final currentBuild = current['buildMillis'];
    if (baselineAnalysis is! int ||
        baselineAnalysis < 0 ||
        baselineBuild is! int ||
        baselineBuild < 0 ||
        currentAnalysis is! int ||
        currentAnalysis < 0 ||
        currentBuild is! int ||
        currentBuild < 0) {
      throw const FormatException('Invalid analysis/build timing metrics.');
    }
    final runner = decoded['runner']! as String;
    final environmentRunner = Platform.environment['DARTITECT_CI_RUNNER_ID'];
    final comparable =
        Platform.environment['CI'] == 'true' && environmentRunner == runner;
    final regressions = <String>[];
    if (comparable) {
      if (currentAnalysis > baselineAnalysis * 1.2) {
        regressions.add(
          'analysisMillis $currentAnalysis > 120% of $baselineAnalysis',
        );
      }
      if (currentBuild > baselineBuild * 1.2) {
        regressions.add('buildMillis $currentBuild > 120% of $baselineBuild');
      }
    }
    return _RecordedPerformance(
      currentAnalysisMillis: currentAnalysis,
      currentBuildMillis: currentBuild,
      comparable: comparable,
      regressions: regressions,
      diagnostic: comparable
          ? 'timings: compared on CI runner $runner with a 20% ratchet'
          : 'timings: runner mismatch or non-CI execution; no ratchet applied',
    );
  }

  String _relative(String path) => path
      .substring(root.path.length + 1)
      .replaceAll(Platform.pathSeparator, '/');
}

final class _GeneratedBudget {
  const _GeneratedBudget({required this.totalBytes, required this.axes});

  final int totalBytes;
  final Map<String, int> axes;
}

_GeneratedBudget _generatedBudget(DartitectConfig config) {
  final profileUnits = config.features.declarations.values.fold<int>(
    0,
    (total, feature) =>
        total +
        switch (feature.profile) {
          FeatureProfile.local => 1,
          FeatureProfile.online => 2,
          FeatureProfile.cache => 3,
          FeatureProfile.replica => 5,
          FeatureProfile.offlineFull => 7,
        },
  );
  final capabilityCount = config.features.declarations.values.fold<int>(
    0,
    (total, feature) => total + feature.capabilities.length,
  );
  final endpointCount = config.features.declarations.values.fold<int>(
    0,
    (total, feature) => total + feature.operations.length,
  );
  final axes = <String, int>{
    'base': 65536,
    'targets': config.targets.platforms.length * 32768,
    'storageContexts': config.storageContexts.length * 65536,
    'transports': config.transports.length * 49152,
    'scheduler': config.scheduler.provider == 'none' ? 0 : 32768,
    'observability': config.observability.provider == 'none' ? 0 : 32768,
    'profiles': profileUnits * 24576,
    'capabilities': capabilityCount * 24576,
    'endpoints': endpointCount * 16384,
    'extensions': config.extensionSources.length * 32768,
  };
  return _GeneratedBudget(
    totalBytes: axes.values.fold<int>(0, (total, value) => total + value),
    axes: Map<String, int>.unmodifiable(axes),
  );
}

String _effectiveProfile(DartitectConfig config) {
  var rank = 0;
  var name = 'local';
  for (final declaration in config.features.declarations.values) {
    final candidate = switch (declaration.profile) {
      FeatureProfile.local => (0, 'local'),
      FeatureProfile.online => (1, 'online'),
      FeatureProfile.cache => (2, 'cache'),
      FeatureProfile.replica => (3, 'replica'),
      FeatureProfile.offlineFull => (4, 'offline-full'),
    };
    if (candidate.$1 > rank) {
      rank = candidate.$1;
      name = candidate.$2;
    }
  }
  return name;
}

Map<String, bool> _capabilityOptIns(DartitectConfig config) => <String, bool>{
  'observability': config.observability.provider != 'none',
  'transport': config.transports.isNotEmpty,
  'storage': config.storageContexts.isNotEmpty,
  'sync': config.features.declarations.values.any(
    (feature) =>
        feature.profile == FeatureProfile.replica ||
        feature.profile == FeatureProfile.offlineFull,
  ),
  'scheduler': config.scheduler.provider != 'none',
};

bool _isGenerated(String path, String source, DartitectConfig config) =>
    path.endsWith('.dartitect.g.dart') ||
    config.generatedSuffixes.any(path.endsWith) ||
    source.startsWith('// GENERATED CODE - DO NOT EDIT');

final class _RecordedPerformance {
  const _RecordedPerformance({
    required this.diagnostic,
    this.currentAnalysisMillis,
    this.currentBuildMillis,
    this.comparable = false,
    this.regressions = const <String>[],
  });

  final int? currentAnalysisMillis;
  final int? currentBuildMillis;
  final bool comparable;
  final List<String> regressions;
  final String diagnostic;
}

const _capabilityPackages = <String, Set<String>>{
  'observability': <String>{
    'dartitect_observability',
    'dartitect_sentry',
    'sentry',
  },
  'transport': <String>{'dio', 'dartitect_dio'},
  'storage': <String>{'drift', 'dartitect_drift'},
  'sync': <String>{'dartitect_sync'},
  'scheduler': <String>{'workmanager', 'dartitect_workmanager'},
};

String _join(String left, String right) =>
    '$left${Platform.pathSeparator}${right.replaceAll('/', Platform.pathSeparator)}';
