import 'dart:convert';
import 'dart:io';

import 'package:dartitect/dartitect.dart' show FeatureProfile;

import '../config/dartitect_config.dart';

/// One consumer-tax ratchet violation.
final class ConsumerTaxFinding {
  /// Creates a path-safe structural or budget finding.
  const ConsumerTaxFinding({
    required this.code,
    required this.message,
    this.path,
    this.evidence,
  });

  /// Stable `DT40xx` code.
  final String code;

  /// Payload-free remediation-oriented summary.
  final String message;

  /// Project-relative path when one file caused the finding.
  final String? path;

  /// Bounded structural evidence with no source bytes.
  final String? evidence;

  /// Stable JSON representation.
  Map<String, Object?> toJson() => <String, Object?>{
    'code': code,
    'message': message,
    if (path != null) 'path': path,
    if (evidence != null) 'evidence': evidence,
  };
}

/// Read-only consumer-tax metrics, ratchets, and findings.
final class ConsumerTaxReport {
  /// Creates a complete deterministic report.
  const ConsumerTaxReport({
    required this.profile,
    required this.metrics,
    required this.budgets,
    required this.capabilityOptIns,
    required this.requiredSymbols,
    required this.unusedDependencies,
    required this.findings,
  });

  /// Report schema version.
  static const int schemaVersion = 1;

  /// Most capable declared feature profile, or `local` for an empty shell.
  final String profile;

  /// Observed counts and optional recorded analysis/build timings.
  final Map<String, Object?> metrics;

  /// Active ratchets for [profile].
  final Map<String, int> budgets;

  /// Explicit config v2 capability selections.
  final Map<String, bool> capabilityOptIns;

  /// Sorted public-looking symbols referenced from Dartitect-importing files.
  final List<String> requiredSymbols;

  /// Direct runtime dependencies with no Dart import in the project.
  final List<String> unusedDependencies;

  /// Blocking structural and ratchet findings.
  final List<ConsumerTaxFinding> findings;

  /// Whether every active ratchet passed.
  bool get isCompliant => findings.isEmpty;

  /// Process exit status.
  int get exitCode => isCompliant ? 0 : 1;

  /// Stable machine-readable report.
  Map<String, Object?> toJson() => <String, Object?>{
    'schemaVersion': schemaVersion,
    'command': 'inspect consumer-tax',
    'profile': profile,
    'compliant': isCompliant,
    'metrics': metrics,
    'budgets': budgets,
    'capabilityOptIns': capabilityOptIns,
    'requiredSymbols': requiredSymbols,
    'unusedDependencies': unusedDependencies,
    'findings': findings.map((finding) => finding.toJson()).toList(),
    'exitCode': exitCode,
  };
}

/// Measures manual structural plumbing and minimal capability closure.
final class ConsumerTaxInspector {
  /// Creates an inspector confined to [root].
  ConsumerTaxInspector(Directory root) : root = root.absolute;

  /// Consumer project boundary.
  final Directory root;

  /// Inspects source, config, dependencies, generated bytes, and recorded time.
  Future<ConsumerTaxReport> inspect() async {
    final timer = Stopwatch()..start();
    final configFile = File(_join(root.path, 'dartitect.json'));
    final config = await configFile.exists()
        ? await DartitectConfig.load(configFile)
        : DartitectConfig(features: DartitectFeaturesConfig());
    final profile = _effectiveProfile(config);
    final budget = Map<String, int>.from(_budgets[profile]!);
    if (config.observability.provider == 'sentry') {
      budget['directDependencyCount'] = budget['directDependencyCount']! + 2;
    }
    final files = await _dartFiles();
    final importedPackages = <String>{};
    final requiredSymbols = <String>{};
    final findings = <ConsumerTaxFinding>[];
    var sourceFiles = 0;
    var sourceLines = 0;
    var generatedFiles = 0;
    var generatedBytes = 0;
    var manualListeners = 0;
    var manualLifecycle = 0;
    var cancellationSources = 0;
    var providerWiring = 0;
    var manualPlumbing = 0;
    var generatedOnceStructuralFiles = 0;

    for (final file in files) {
      final relative = _relative(file.path);
      final source = await file.readAsString();
      final generated = _isGenerated(relative, source, config);
      for (final match in _packageImport.allMatches(source)) {
        importedPackages.add(match.group(1)!);
      }
      if (generated) {
        generatedFiles += 1;
        generatedBytes += await file.length();
        continue;
      }
      sourceFiles += 1;
      sourceLines += '\n'.allMatches(source).length + 1;
      manualListeners += _listener.allMatches(source).length;
      manualLifecycle += _lifecycle.allMatches(source).length;
      cancellationSources += _cancellation.allMatches(source).length;
      providerWiring += _providerImport.allMatches(source).length;
      if (_dartitectImport.hasMatch(source)) {
        requiredSymbols.addAll(
          _publicSymbol
              .allMatches(source)
              .map((match) => match.group(0)!)
              .where((name) => !_languageSymbols.contains(name)),
        );
      }
      for (final rule in _structuralRules) {
        final matches = rule.pattern.allMatches(source).length;
        if (matches == 0) continue;
        manualPlumbing += matches;
        findings.add(
          ConsumerTaxFinding(
            code: rule.code,
            message: rule.message,
            path: relative,
            evidence: '${rule.label}: $matches',
          ),
        );
      }
      final structuralMarkers = _structuralMarkers
          .where((pattern) => pattern.hasMatch(source))
          .length;
      if (structuralMarkers >= 2) {
        generatedOnceStructuralFiles += 1;
        manualPlumbing += 1;
        findings.add(
          ConsumerTaxFinding(
            code: 'DT4004',
            message:
                'Pure assembly plumbing must be a managed generated output.',
            path: relative,
            evidence: '$structuralMarkers structural markers',
          ),
        );
      }
    }

    final directDependencies = await _directDependencies();
    final unusedDependencies =
        directDependencies
            .where(
              (dependency) =>
                  dependency != 'flutter' &&
                  dependency.startsWith('dartitect') &&
                  !importedPackages.contains(dependency),
            )
            .toList()
          ..sort();
    for (final dependency in unusedDependencies) {
      findings.add(
        ConsumerTaxFinding(
          code: 'DT4005',
          message: 'A direct Dartitect dependency is unused.',
          path: 'pubspec.yaml',
          evidence: dependency,
        ),
      );
    }
    final optIns = _capabilityOptIns(config);
    final resolved = await _resolvedDependencies(directDependencies);
    for (final capability in _capabilityPackages.entries) {
      if (optIns[capability.key] == true) continue;
      final unexpected = capability.value.intersection(resolved).toList()
        ..sort();
      for (final dependency in unexpected) {
        findings.add(
          ConsumerTaxFinding(
            code: 'DT4006',
            message:
                'A capability dependency is resolved without config opt-in.',
            path: 'pubspec.yaml',
            evidence: '${capability.key}: $dependency',
          ),
        );
      }
    }

    final recorded = await _recordedPerformance();
    timer.stop();
    final metrics = <String, Object?>{
      'manualPlumbing': manualPlumbing,
      'manualListeners': manualListeners,
      'manualLifecycle': manualLifecycle,
      'cancellationSources': cancellationSources,
      'providerSpecificWiring': providerWiring,
      'requiredSymbolCount': requiredSymbols.length,
      'generatedOnceStructuralFiles': generatedOnceStructuralFiles,
      'unusedDependencyCount': unusedDependencies.length,
      'directDependencyCount': directDependencies.length,
      'sourceFiles': sourceFiles,
      'sourceLines': sourceLines,
      'generatedFiles': generatedFiles,
      'generatedBytes': generatedBytes,
      'inspectionMillis': timer.elapsedMilliseconds,
      'analysisMillis': recorded.analysisMillis,
      'buildMillis': recorded.buildMillis,
    };
    _enforceBudget(metrics, budget, findings);
    findings.sort((left, right) {
      final code = left.code.compareTo(right.code);
      return code != 0 ? code : '${left.path}'.compareTo('${right.path}');
    });
    final symbols = requiredSymbols.toList()..sort();
    return ConsumerTaxReport(
      profile: profile,
      metrics: Map<String, Object?>.unmodifiable(metrics),
      budgets: Map<String, int>.unmodifiable(budget),
      capabilityOptIns: Map<String, bool>.unmodifiable(optIns),
      requiredSymbols: List<String>.unmodifiable(symbols),
      unusedDependencies: List<String>.unmodifiable(unusedDependencies),
      findings: List<ConsumerTaxFinding>.unmodifiable(findings),
    );
  }

  Future<List<File>> _dartFiles() async {
    final output = <File>[];
    for (final directory in <Directory>[Directory(_join(root.path, 'lib'))]) {
      if (!await directory.exists()) continue;
      await for (final entity in directory.list(
        recursive: true,
        followLinks: false,
      )) {
        if (entity is File && entity.path.endsWith('.dart')) output.add(entity);
      }
    }
    final packages = Directory(_join(root.path, 'packages'));
    if (await packages.exists()) {
      await for (final entity in packages.list(followLinks: false)) {
        if (entity is! Directory) continue;
        final lib = Directory(_join(entity.path, 'lib'));
        if (!await lib.exists()) continue;
        await for (final child in lib.list(
          recursive: true,
          followLinks: false,
        )) {
          if (child is File && child.path.endsWith('.dart')) output.add(child);
        }
      }
    }
    output.sort((left, right) => left.path.compareTo(right.path));
    return output;
  }

  Future<Set<String>> _directDependencies() async {
    final pubspec = File(_join(root.path, 'pubspec.yaml'));
    if (!await pubspec.exists()) return <String>{};
    final output = <String>{};
    var dependencies = false;
    for (final line in await pubspec.readAsLines()) {
      if (line == 'dependencies:') {
        dependencies = true;
        continue;
      }
      if (dependencies && line.isNotEmpty && !line.startsWith(' ')) break;
      final match = dependencies
          ? RegExp(r'^  ([a-zA-Z][a-zA-Z0-9_]*):').firstMatch(line)
          : null;
      if (match != null) output.add(match.group(1)!);
    }
    return output;
  }

  Future<Set<String>> _resolvedDependencies(Set<String> direct) async {
    final lock = File(_join(root.path, 'pubspec.lock'));
    if (!await lock.exists()) return direct;
    final output = <String>{};
    var packages = false;
    for (final line in await lock.readAsLines()) {
      if (line == 'packages:') {
        packages = true;
        continue;
      }
      if (packages && line.isNotEmpty && !line.startsWith(' ')) break;
      final match = packages
          ? RegExp(r'^  ([a-zA-Z][a-zA-Z0-9_]*):$').firstMatch(line)
          : null;
      if (match != null) output.add(match.group(1)!);
    }
    return output.isEmpty ? direct : output;
  }

  Future<_RecordedPerformance> _recordedPerformance() async {
    final file = File(_join(root.path, '.dartitect/consumer-tax-metrics.json'));
    if (!await file.exists()) return const _RecordedPerformance();
    final decoded = jsonDecode(await file.readAsString());
    if (decoded is! Map<String, Object?> || decoded['schemaVersion'] != 1) {
      throw const FormatException('Invalid consumer-tax performance metrics.');
    }
    final analysis = decoded['analysisMillis'];
    final build = decoded['buildMillis'];
    if (analysis is! int || analysis < 0 || build is! int || build < 0) {
      throw const FormatException('Invalid analysis/build timing metrics.');
    }
    return _RecordedPerformance(analysisMillis: analysis, buildMillis: build);
  }

  String _relative(String path) => path
      .substring(root.path.length + 1)
      .replaceAll(Platform.pathSeparator, '/');
}

void _enforceBudget(
  Map<String, Object?> metrics,
  Map<String, int> budgets,
  List<ConsumerTaxFinding> findings,
) {
  for (final budget in budgets.entries) {
    final observed = metrics[budget.key];
    if (observed is! int || observed <= budget.value) continue;
    findings.add(
      ConsumerTaxFinding(
        code: budget.key == 'analysisMillis' || budget.key == 'buildMillis'
            ? 'DT4008'
            : 'DT4007',
        message: 'Consumer-tax ratchet exceeded for ${budget.key}.',
        evidence: '$observed > ${budget.value}',
      ),
    );
  }
}

String _effectiveProfile(DartitectConfig config) {
  var rank = 0;
  var name = 'local';
  for (final declaration in config.features.declarations.values) {
    final candidate = switch (declaration.profile) {
      FeatureProfile.local => (0, 'local'),
      FeatureProfile.online => (1, 'online'),
      FeatureProfile.cache => (2, 'cache'),
      FeatureProfile.replica => (3, 'replica'),
      FeatureProfile.offlineFull => (4, 'offline-full'),
    };
    if (candidate.$1 > rank) {
      rank = candidate.$1;
      name = candidate.$2;
    }
  }
  return name;
}

Map<String, bool> _capabilityOptIns(DartitectConfig config) => <String, bool>{
  'observability': config.observability.provider != 'none',
  'transport': config.transports.isNotEmpty,
  'storage': config.storageContexts.isNotEmpty,
  'sync': config.features.declarations.values.any(
    (feature) =>
        feature.profile == FeatureProfile.replica ||
        feature.profile == FeatureProfile.offlineFull,
  ),
  'scheduler': config.scheduler.provider != 'none',
};

bool _isGenerated(String path, String source, DartitectConfig config) =>
    path.endsWith('.dartitect.g.dart') ||
    config.generatedSuffixes.any(path.endsWith) ||
    source.startsWith('// GENERATED CODE - DO NOT EDIT');

final class _RecordedPerformance {
  const _RecordedPerformance({this.analysisMillis, this.buildMillis});

  final int? analysisMillis;
  final int? buildMillis;
}

final class _StructuralRule {
  const _StructuralRule(this.code, this.label, this.message, this.pattern);

  final String code;
  final String label;
  final String message;
  final RegExp pattern;
}

final _packageImport = RegExp(r'''import\s+['"]package:([^/]+)/''');
final _dartitectImport = RegExp(r'''import\s+['"]package:dartitect''');
final _providerImport = RegExp(
  r'''import\s+['"]package:(?:dio|drift|objectbox|workmanager)/''',
);
final _publicSymbol = RegExp(r'\b[A-Z][A-Za-z0-9_]*\b');
final _listener = RegExp(r'\.(?:addListener|removeListener|listen)\s*\(');
final _lifecycle = RegExp(r'\.(?:dispose|disposeAsync|close|cancel)\s*\(');
final _cancellation = RegExp(r'\b(?:CancellationSource|CancelToken)\s*\(');

final _structuralRules = <_StructuralRule>[
  _StructuralRule(
    'DT4000',
    'untyped capability slot',
    'Capability slots in consumer composition must be concretely typed.',
    RegExp(
      r'\bObject\?\s+(?:repository|storage|transport|scheduler|observability|sync|outbox|engine|owner)\b',
    ),
  ),
  _StructuralRule(
    'DT4001',
    'null capability slot',
    'Absent capabilities must not leave nullable composition slots.',
    RegExp(
      r'\b(?:repository|storage|transport|scheduler|observability|sync|outbox|engine|owner)\s*:\s*null\b',
    ),
  ),
  _StructuralRule(
    'DT4002',
    'provider owner',
    'Provider owner plumbing belongs in managed generated composition.',
    RegExp(r'\b(?:DioOwner|DriftDatabaseOwner|ObjectBoxStoreOwner)\s*[.(]'),
  ),
  _StructuralRule(
    'DT4003',
    'manual engine',
    'SDK engine construction belongs in managed generated composition.',
    RegExp(
      r'\b(?:SyncEngine|MutationCommand|BootstrapCoordinator|HeadlessSyncEndpoint)\s*\(',
    ),
  ),
];

final _structuralMarkers = <RegExp>[
  RegExp(r'\bDartitectAssemblyBinding\b'),
  RegExp(r'\bOwnedGraph\b'),
  RegExp(r'\bFeatureAssembly\b'),
  RegExp(r'\bApplicationModule\b'),
  RegExp(r'\bSessionModule\b'),
];

const _languageSymbols = <String>{
  'Dart',
  'Future',
  'FutureOr',
  'List',
  'Map',
  'Object',
  'Set',
  'String',
};

const _capabilityPackages = <String, Set<String>>{
  'observability': <String>{
    'dartitect_observability',
    'dartitect_sentry',
    'sentry',
  },
  'transport': <String>{'dio', 'dartitect_dio'},
  'storage': <String>{'drift', 'dartitect_drift'},
  'sync': <String>{'dartitect_sync'},
  'scheduler': <String>{'workmanager', 'dartitect_workmanager'},
};

const _budgets = <String, Map<String, int>>{
  'local': <String, int>{
    'manualPlumbing': 0,
    'manualListeners': 4,
    'manualLifecycle': 8,
    'cancellationSources': 2,
    'providerSpecificWiring': 2,
    'requiredSymbolCount': 120,
    'generatedOnceStructuralFiles': 0,
    'unusedDependencyCount': 0,
    'directDependencyCount': 5,
    'sourceFiles': 50,
    'generatedBytes': 131072,
    'analysisMillis': 60000,
    'buildMillis': 300000,
  },
  'online': <String, int>{
    'manualPlumbing': 0,
    'manualListeners': 6,
    'manualLifecycle': 12,
    'cancellationSources': 4,
    'providerSpecificWiring': 4,
    'requiredSymbolCount': 180,
    'generatedOnceStructuralFiles': 0,
    'unusedDependencyCount': 0,
    'directDependencyCount': 8,
    'sourceFiles': 80,
    'generatedBytes': 196608,
    'analysisMillis': 90000,
    'buildMillis': 360000,
  },
  'cache': <String, int>{
    'manualPlumbing': 0,
    'manualListeners': 8,
    'manualLifecycle': 16,
    'cancellationSources': 5,
    'providerSpecificWiring': 6,
    'requiredSymbolCount': 240,
    'generatedOnceStructuralFiles': 0,
    'unusedDependencyCount': 0,
    'directDependencyCount': 10,
    'sourceFiles': 110,
    'generatedBytes': 262144,
    'analysisMillis': 120000,
    'buildMillis': 420000,
  },
  'replica': <String, int>{
    'manualPlumbing': 0,
    'manualListeners': 10,
    'manualLifecycle': 20,
    'cancellationSources': 6,
    'providerSpecificWiring': 8,
    'requiredSymbolCount': 320,
    'generatedOnceStructuralFiles': 0,
    'unusedDependencyCount': 0,
    'directDependencyCount': 12,
    'sourceFiles': 140,
    'generatedBytes': 393216,
    'analysisMillis': 150000,
    'buildMillis': 480000,
  },
  'offline-full': <String, int>{
    'manualPlumbing': 0,
    'manualListeners': 12,
    'manualLifecycle': 24,
    'cancellationSources': 8,
    'providerSpecificWiring': 10,
    'requiredSymbolCount': 400,
    'generatedOnceStructuralFiles': 0,
    'unusedDependencyCount': 0,
    'directDependencyCount': 16,
    'sourceFiles': 180,
    'generatedBytes': 524288,
    'analysisMillis': 180000,
    'buildMillis': 540000,
  },
};

String _join(String left, String right) =>
    '$left${Platform.pathSeparator}${right.replaceAll('/', Platform.pathSeparator)}';
