name: dartitect_devtools_extension_web
description: Flutter Web source for the read-only Dartitect DevTools extension.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.13.0

dependencies:
  devtools_extensions: ^0.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
